name: Test Self-Hosted Runner

on:
  workflow_dispatch: # Lancement manuel depuis GitHub

jobs:
  test-run:
    runs-on: self-hosted
    steps:
      - name: Afficher un message
        run: echo "ğŸ‰ Le runner auto-hÃ©bergÃ© fonctionne correctement !"
